name: mindrover-europa # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.07a' # just for humans, typically '1.2+git' or '1.3.2'
summary: A retro tank game
description: |
  A retro tank game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mindrover_icon.png
title: Mindrover - The Europa Project

apps:
  mindrover:
    command: mindrover
parts:
  mindrover:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mindrover: build/
      mindrover.1: man/man1/

architectures:
  - build-on: amd64

